export type VideoSegment = {start:number;end:number};
export const MIN_CLIP: number;
export const MAX_CLIPS: number;
export function validVideoRange(start:number,end:number,duration:number):boolean;
export function validSegments(segments:VideoSegment[],duration:number):boolean;
export function videoTimeLabel(seconds:number):string;
export function splitSegment(segments:VideoSegment[],time:number):VideoSegment[];
export function trimSegment(segments:VideoSegment[],index:number,edge:'start'|'end',value:number,duration:number):VideoSegment[];
export function timelineDuration(segments:VideoSegment[]):number;
export function nextPlayableTime(segments:VideoSegment[],time:number):number|null;
export function outputTime(segments:VideoSegment[],sourceTime:number):number;
export function deletedRanges(segments:VideoSegment[],duration:number):VideoSegment[];
